spring:
  application:
    name: server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/pet_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: lhf20040208
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: true
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml #mapper文件的路径
  type-aliases-package: com.lee.server.entity #实体类的包路径

server:
  port: 8080
  servlet:
    context-path: /     #项目访问路径
    session:
      cookie:
        max-age: 1800   #cookie过期时间
      timeout: 1800    #session过期时间
  tomcat:
    uri-encoding: utf-8
    threads:
      min-spare: 25
      max: 200
logging:
  file:
    name: server.log
  level:
    root: info
    com.three.server: debug
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#debug: true



